POST http://localhost:8080/mxl
Content-Type: text/plain

{
|----------|----------1-------|
|----------|--4---------1-----|
|--3b5-3---|--3b5-5b6-----3b5-|
|----------|------------------|
|----------|------------------|
|----------|------------------|
}


###
###
GET http://localhost:8080/mxlError

<> 2022-04-22T193314.200.json




###
